version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    environment: 
      IMAGE_TAG: ghcr.io/jtaylorsoftware/tictactoe
    steps:
      - checkout
      # Run unit tests
      - run: docker build -t test --target test .
      - run: docker run -it --rm test
      # Build image and persist
      - run: docker build -t $IMAGE_TAG -f build/Dockerfile --target prod .
      - run: mkdir -p ./images && docker save -o ./images/production.tar $IMAGE_TAG
      - persist_to_workspace:
          root: .
          paths:
            - ./images
  push-image:
    machine:
      image: "ubuntu-1604:202004-01"
      docker_layer_caching: true
    environment: 
      IMAGE_TAG: ghcr.io/jtaylorsoftware/tictactoe
    steps:
      - attach_workspace:
          at: .
      # Login to ghcr
      - run: |
          echo "$GHCR_PAT" | docker login ghcr.io -u jtaylorsoftware --password-stdin
      # Load built image
      - run: docker load -i ./images/production.tar
      # Publish to ghcr
      - run: docker push $IMAGE_TAG

workflows:
  build-push:
    jobs:
      - build
      - push-image:
          requires:
            - build
          context:
            - ghcr
